# site settings
title: Sydni Fomas Do
subtitle: Marketing Ph.D. Candidate
email: Sydnifdo@arizona.edu
remote_theme: Forty
description: Sydni Fomas Do is a fourth-year marketing doctoral student at the University of Arizona Eller College of Management. With a research focus that spans topics such as financial decision-making, stereotype threat, and brand activism, her work addresses contemporary marketing challenges, including how the marketplace can improve the well-being of underrepresented and vulnerable populations.
baseurl: "/profile" # the subpath of your site, e.g. /blog
url: "www.sydnifomasdo.com" # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: United States of America
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Scholar: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/sydnifdo/
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
